### PR TITLE
Expose predict proba

### PR DESCRIPTION
**Pull request by sahilshah1194**
[please review the [contribution guidelines](http://rhiever.github.io/tpot/contributing/) prior to submitting your pull request. go ahead and delete this line if you've already reviewed said guidelines.]
## What does this PR do?

Exposes the predict_proba and predict_log_proba functions of the scikit-learn classifiers and regressers
## Any background context you want to provide?

https://github.com/rhiever/tpot/issues/276

### CODE REVIEW

**Comment by weixuanfu2016** [comment]
Not all operators in scikit-learn has predict_proba (e.g 'GradientBoostingRegressor' object has no attribute 'predict_proba' ). Maybe you could add a exception for these operators.

**Comment by sahilshah1194** [comment]
GradientBoostingRegressor does have a predict_proba. It seems like all of them do, from the conversation I linked and also additional verifications.

**Comment by weixuanfu2016** [comment]
import numpy as np
import matplotlib.pyplot as plt

from sklearn import ensemble
from sklearn import datasets
from sklearn.utils import shuffle
from sklearn.metrics import mean_squared_error

boston = datasets.load_boston()
X, y = shuffle(boston.data, boston.target, random_state=13)
X = X.astype(np.float32)
offset = int(X.shape[0] * 0.9)
X_train, y_train = X[:offset], y[:offset]
X_test, y_test = X[offset:], y[offset:]

params = {'n_estimators': 500, 'max_depth': 4, 'min_samples_split': 2,
          'learning_rate': 0.01, 'loss': 'ls'}
clf = ensemble.GradientBoostingRegressor(**params)

clf.fit(X_train, y_train)
mse = mean_squared_error(y_test, clf.predict(X_test))
print("MSE: %.4f" % mse)

print(clf.predict_proba())



Try the codes. Somehow I got this message

>>> print("MSE: %.4f" % mse)
MSE: 6.7976
>>>
>>> print(clf.predict_proba())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'GradientBoostingRegressor' object has no attribute 'predict_proba'

**Comment by sahilshah1194** [comment]
Ok nevermind I see it now. Should I put this around a try statement and raise an exception? What do you think the best design is?

**Comment by weixuanfu2016** [comment]
I suggest use "if hasattr(clf, "predict_proba"):" to find out whether operator has the predict_proba object. Check this [Probability calibration](http://scikit-learn.org/stable/modules/calibration.html#probability-calibration). Maybe CalibratedClassifierCV can be help for Classifier. Not sure whether it is reasonable for regressor. 

Example code:

```
import numpy as np
np.random.seed(0)

import matplotlib.pyplot as plt

from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.calibration import calibration_curve

X, y = datasets.make_classification(n_samples=100000, n_features=20,
                                    n_informative=2, n_redundant=2)

train_samples = 100  # Samples used for training the models

X_train = X[:train_samples]
X_test = X[train_samples:]
y_train = y[:train_samples]
y_test = y[train_samples:]


svc = LinearSVC(C=1.0)
svc.fit(X_train, y_train)
print(svc.predict_proba(X_test)) ## AttributeError: 'LinearSVC' object has no attribute 'predict_proba'
clf = CalibratedClassifierCV(svc) 
clf.fit(X_train, y_train)
y_proba = clf.predict_proba(X_test)  ## report probililty
```

**Comment by sahilshah1194** [comment]
This makes sense. Although I'm not exactly sure what kind of calibrator to use. Should that be a parameter that they can pass in?

**Comment by sahilshah1194** [comment]
```
    def predict_proba(self, features, classifier_type='isotonic'):
        """Uses the optimized pipeline to estimate the class probabilities for a feature set

        Parameters
        ----------
        features: array-like {n_samples, n_features}
            Feature matrix of the testing set
        classifier_type: string (default: 'isotonic')
            Type of classifier to be used when creating a CalibratedClassifier

        Returns
        -------
        array-like: {n_samples, n_classes}
            The class probabilities of the input samples

        """
        if not self._fitted_pipeline:
            raise ValueError('A pipeline has not yet been optimized. Please call fit() first.')
        else:
            if not(hasattr(self._fitted_pipeline, 'predict_proba')):
            #Would need to create calibrator object
            #Would need to re-fit data
            return self._fitted_pipeline.predict_proba(features.astype(np.float64))
```

**Comment by weixuanfu2016** [comment]
Yes, separate operations are a good idea.

**Comment by weixuanfu2016** [comment]
Please check the cv = "prefit" parameter in [CalibratedClassifierCV](http://scikit-learn.org/stable/modules/generated/sklearn.calibration.CalibratedClassifierCV.html#sklearn.calibration.CalibratedClassifierCV). It shows that "If “prefit” is passed, it is assumed that base_estimator has been fitted already and all data is used for calibration." Is it what you are looking for?

**Comment by weixuanfu2016** [comment]
It is not advised to use isotonic calibration with too few calibration samples (<<1000) since it tends to overfit. Use sigmoids (Platt’s calibration) in this case. Maybe we should set 'sigmoids' as default.

Also, calibrator still need fit even with cv = 'prefit' (why?) and the predict_proba is not exactly same as that from direct classier.

I found a [case](http://stackoverflow.com/questions/30285551/why-does-calibratedclassifiercv-underperform-a-direct-classifer) online. 
I revised a little their codes for testing isotonic method

Try the codes here:

```
from sklearn.datasets import make_classification
from sklearn import ensemble
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import log_loss
from sklearn import cross_validation

# Build a classification task using 3 informative features

X, y = make_classification(n_samples=1000,
                           n_features=100,
                           n_informative=30,
                           n_redundant=0,
                           n_repeated=0,
                           n_classes=9,
                           random_state=0,
                           shuffle=False)

skf = cross_validation.StratifiedShuffleSplit(y, 5)

for train, test in skf:

    X_train, X_test = X[train], X[test]
    y_train, y_test = y[train], y[test]

    clf = ensemble.GradientBoostingClassifier(n_estimators=50)
    clf.fit(X_train, y_train)
    probas = clf.predict_proba(X_test)
    clf_score = log_loss(y_test, probas)
    clf_cv1 = CalibratedClassifierCV(clf, cv="prefit", method='sigmoid')
    clf_cv1.fit(X_train, y_train)
    probas_cv1 = clf_cv1.predict_proba(X_test)
    cv_score1 = log_loss(y_test, probas_cv1)
    clf_cv2 = CalibratedClassifierCV(clf, cv="prefit", method='isotonic')
    clf_cv2.fit(X_train, y_train)
    probas_cv2 = clf_cv2.predict_proba(X_test)
    cv_score2 = log_loss(y_test, probas_cv2)
```

**Comment by sahilshah1194** [comment]
So there is a case when the calibrated classifier actually performs worse. I don't think that we should be the ones internally tracking the best way to predict probabilities. This is something the user should do. 

Thus, should we include a boolean flag inputted to predict_proba that allows the user to specify whether they want us to use the calibrated classifier or not?

**Comment by rhiever** [comment]
@sahilshah1194, please send this branch as a PR to the `development` branch. I had to un-merge it from the `master` branch and can't re-open this PR.

**Pull request merged**
