### PR TITLE
Use stopit module for timeout function

### PR DESCRIPTION
**Pull request by weixuanfu2016**
## What does this PR do?

1. Remove `Interruptable_cross_val_score` class since it cannot stop thread cleanly.

2. `stopit` module can raise a Exception in a working thread for stopping thread and has a better decorator for timeout function

3. Because Ctrl + C works with n_jobs is not 1 in Windows OS after using`stopit` module, the related warning message was removed

## Where should the reviewer start?

[gp_deap.py](https://github.com/weixuanfu2016/tpot/blob/03eed0d14b917ff21b5d39314a5d8435ebe64590/tpot/gp_deap.py#L335)

## How should this PR be tested?

Any TPOT examples

## What are the relevant issues?

#508 

## Questions:

- Do the docs need to be updated? Yes, updated in the PR
- Does this PR add new (Python) dependencies? Yes, need stopit module

### CODE REVIEW

**Comment by weixuanfu2016** [comment]
Update: 

After more tests, freezing issue #436 and #422 are also fixed somehow in Windows OS. Test codes:

```
# coding: utf-8
from sklearn.datasets import make_classification
from tpot import TPOTClassifier
# make a huge dataset
X, y = make_classification(n_samples=50000, n_features=200,
                                    n_informative=20, n_redundant=20,
                                    n_classes=5, random_state=42)

# max_eval_time_mins=0.1 means 6 seconds limits for evaluating a single pipeline 
tpot = TPOTClassifier(generations=5, population_size=50, offspring_size=100, random_state=42, n_jobs=1, max_eval_time_mins=0.1, verbosity=3) 
tpot.fit(X, y)```

**Comment by rhiever** [comment]
Future note (also to @teaearlgraycold): Please don't rebuild the docs in future PRs. That's an easy way to get ugly merge conflicts.

**Comment by weixuanfu2016** [comment]
OK, I will restore changes in docs.

**Comment by weixuanfu2016** [comment]
Changes in docs was reverted.

**Pull request merged**
