### PR TITLE
New point mutation operator

### PR DESCRIPTION
**Pull request by weixuanfu2016**
## What does this PR do?

A new point mutation operator is added and it replaces a randomly chosen primitive/terminal (operator/parameter). It is noted that the old point mutation operator mentioned in the issue #318 was `gp.mutUniform`, which is not exactly point mutation operator since it changes all subsequent steps in a pipeline  from the mutated points. The new point mutation operator can keep all the subsequent and only change one parameter or one operator (with randomly generating whole set of its parameters).

## Where should the reviewer start?

line 617 in base.py

## How should this PR be tested?

Any TPOT examples.

## What are the relevant issues?

#318 

## Questions:

As mentioned above, `gp.mutUniform` is not real point mutation function. But in the PR, I still keep in TPOT as one of 4 random mutation operators. I am not sure whether it should be removed.

Another concern is that the new point mutation can change the whole "pipeline" if the pipeline only has one operator and the mutated point is the primitive. The default mutation rate in TPOT is 0.9, which maybe too high to save good pipeline when generating a new generation by mutation.

### CODE REVIEW

**Comment by rhiever** [comment]
Can you please bring this PR up to date with the latest of the `development` branch?

Also, maybe we should move all of the GP-related functions to `deap_gp.py`.

**Comment by weixuanfu2016** [comment]
OK, make sense.

**Comment by rhiever** [comment]
Latest commits seem to break. Something about a `NoneType` not being iterable.

**Comment by weixuanfu2016** [comment]
Yep, I am looking into it. The reason is somehow the `self._optimized_pipeline` is NoneType. And both unit tests used the fit() with population_size = 1 and generations = 1. My guess is that a random pipeline failed and then was assign a `-float(inf)` score  but this error was not caught. I will fix the bug soon.

**Comment by rhiever** [comment]
Yep, I suspect that is the error as well.

**Comment by weixuanfu2016** [comment]
The bugs should be fixed.

**Pull request merged**
