### PR TITLE
Arbitrary scoring functions + doc example

### PR DESCRIPTION
**Pull request by bartleyn**
Per #33 , I've taken a stab at the arbitrary scoring function implementation, and wrote an example using scoring functions written in the same vein as the original balanced accuracy calculation.

### CODE REVIEW

**Comment by rhiever** [comment]
Looks good to me. Thoughts @rasbt?

**Comment by rhiever** [comment]
Merging this now. Thank you @bartleyn!

**Comment by bartleyn** [comment]
I'm happy to take another look and see if there's a smarter/more efficient way to handle this -- I imagine passing the dataframes to the scoring function will get bulky after a point.

**Comment by rhiever** [comment]
We're definitely open to suggestions. :-) It's nice having DataFrames because you can (theoretically) maintain the names of the columns through the whole process, which helps with inspection if you're, e.g., looking at feature importance scores.

**Pull request merged**
