### PR TITLE
Docstrings & Private Methods

### PR DESCRIPTION
**Pull request by rasbt**
I added the docstrings to the public methods, please double-check if this is correct in its meaning :).
Also, I made the internal methods private so that a user is not confused when he/she calls help(TPOT)

### CODE REVIEW

**Comment by rasbt** [comment]
Hah, weird, somehow my local nosetest didn't complain ... have to look into this ...

**Comment by rhiever** [comment]
I imagine the tests are failing because those private methods are no longer available for inspection.

**Comment by rasbt** [comment]
> I imagine the tests are failing because those private methods are no longer available for inspection.

Yes, and I was running nosetests in the tpot/tpot dir so that it actually didn't run the tests.py at all :P

**Comment by rhiever** [comment]
Ah yes, that would do it. :-)

I'm wondering if the tests should be moved to a separate directory.

**Comment by JanSchulz** [comment]
@rasbt Are these all completely handcrafted docstrings or do you have a tool for that?

**Comment by rasbt** [comment]
@JanSchulz 
These were all "manually" written, I don't think this can be done via a tool (since it need to guess your intention as programmer). But maybe we can automate the type-checking part some day ;) (https://www.python.org/dev/peps/pep-0484/)

**Comment by JanSchulz** [comment]
@rasbt Ok, thought you have a tool which at least generate some of the stuff... I currently use pycharm at it at least generates  the structure and the names of the variables...

**Pull request merged**
