### PR TITLE
Adding the Titanic Kaggle tutorial

### PR DESCRIPTION
**Pull request by pronojitsaha**
Tutorial for using TPOT on the Kaggle Titanic dataset. 

@rhiever Let me know if you want to add or change something?

### CODE REVIEW

**Comment by rhiever** [comment]
:+1: I'm pretty tight on time while conferencing, but I plan to review this PR when I get back. Cheers!

**Comment by pronojitsaha** [comment]
Ok, I understand. Have a good one..All the best!

**Comment by pronojitsaha** [comment]
Hi @rhiever , would you want me to change something for this PR? 

Also I was thinking of digging deeper into #61 , is that ok?

**Comment by rhiever** [comment]
It will probably be worth rerunning and recommitting the notebook with the
latest version of TPOT. Quite a bit has changed with the addition of Pareto
optimization. Please ping me when that is done and I will take a closer
look.

On Thu, Feb 18, 2016 at 11:15 AM, PRONOjit Saha <notifications@github.com>
wrote:

> Hi @rhiever <https://github.com/rhiever> , would you want me to change
> something for this PR?
>
> Also I was thinking of digging deeper into #61
> <https://github.com/rhiever/tpot/issues/61> , is that ok?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/tpot/pull/71#issuecomment-185796612>.
>



-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by pronojitsaha** [comment]
Ok..sure.

**Comment by rhiever** [comment]
Working through PRs this morning. I'll merge and rerun it. Thanks again @pronojitsaha!

**Comment by pronojitsaha** [comment]
Ok...great! Thanks.

**Pull request merged**
