### PR TITLE
cross_val_score scoring_function support

### PR DESCRIPTION
**Pull request by bartleyn**
## What does this PR do?

1. Addresses #238, allowing use for compatible loss/error functions and having TPOT takes the best pipeline when using log_loss. 
2. Uses sklearn's get_scorer function to validate strings passed in a scoring_function are valid (for cross_val_score), and restricts use of custom functions. 
3. Tweaks the instantiator test to reflect the above changes. 

## Where should the reviewer start?

tpot.py:__init__()
tpot.py:fit()
tpot.py:_evaluate_individual()

## How should this PR be tested?

Making sure that the fitted pipelines 

## Any background context you want to provide?

1. Some scoring functions implemented in sklearn only allow for binary classification, causing pipelines to raise exceptions if the data is multiclass.
2.  `log_loss` needs predict_proba support. This may restrict the classifier operators used in the final pipelines to those that support that functionality. 

## What are the relevant issues?

#238 

## Questions:

- Do the docs need to be updated?
No, as the docs already reflect that strings should be passed in as the scoring_function parameter.
- Does this PR add new (Python) dependencies?
No

### CODE REVIEW

**Comment by teaearlgraycold** [comment]
Why restrict scoring_function to strings? We already need to use functions as scoring functions due to balanced_accuracy.

**Comment by bartleyn** [comment]
I made that decision because that was how I interpreted #238 and the decision to restrict possible functions to those supported by cross_val_score. I can revert that change (and will since it seems to break the build around fetching the params). 

I guess the question is, what do we allow then? We can go completely the way of `cross_val_score()` and allow both the appropriate strings and all callables with the signature `scorer(estimator, X, y)`. However, since we don't actually evaluate the scoring_function until we call `cross_val_score()` within `_evaluate_individual()`, any malformed scoring_functions will invalidate every pipeline (since we have that catchall Exception handler). What do you think would be elegant for this? Is a check for three args going to suffice?

**Comment by teaearlgraycold** [comment]
We're already adding code to tell users what went wrong when all pipelines fail to evaluate.

As is standard with Python, you just have to trust the user will pass valid objects as parameters.

**Comment by bartleyn** [comment]
Per your note, I've removed the input validation, and updated some of the info regarding scoring functions in the docs.

**Pull request merged**
