### PR TITLE
Add get_params function to TPOT to mimic the sklearn interface

### PR DESCRIPTION
**Pull request by teaearlgraycold**
## What does this PR do?

Adds a new member function to the TPOT class that returns the inputted parameters of TPOT

## Where should the reviewer start?

`TPOT.get_params()`

## How should this PR be tested?

A test was added for the get_params method, it can be seen in test_get_params in the tests.py module

## What are the relevant issues?

#142

### CODE REVIEW

**Comment by rhiever** [comment]
Can you do a quick verification w/ this change to see if it allows TPOT to be used in sklearn's cross_val_score?

**Comment by teaearlgraycold** [comment]
Already did that and it ran successfully.

**Comment by rhiever** [comment]
In that test case, `tpot` was a TPOT object you instantiated?

**Comment by teaearlgraycold** [comment]
Yes

**Comment by rhiever** [comment]
BTW: You can name PRs `Fixed #[issue num]` and they will automatically close the named issue when the PR is merged.

**Comment by teaearlgraycold** [comment]
Okay. That's neat

**Pull request merged**
