### PR TITLE
One hot encoder

### PR DESCRIPTION
**Pull request by teaearlgraycold**
## What does this PR do?

* Adds the autosklearn one hot encoder
* Adds two new config dictionaries with sklearn operators that support sparse matrices
* Refactors tests into a tests directory, broken into multiple files

## Where should the reviewer start?

* `tpot/one_hot_encoder.py`
* `tests/*.py`
* `TPOTBase._setup_config`

I have not made any changes to the docs yet.

All credit to @slcott who originally PR'd these changes.

### CODE REVIEW

**Comment by rhiever** [comment]
Looks like this needs to be rebased with your latest repo reorganization PR.

**Comment by rhiever** [comment]
@teaearlgraycold, can you please rebase this today (or ASAP) so we can merge it and release 0.8? I believe this is the last major PR that we'll merge before testing and release.

**Comment by rhiever** [comment]
Ah right, I just remembered that this PR will need significant rework per our private discussions. We will slate this PR for a 0.8.1 release.

**Comment by weixuanfu2016** [comment]
This PR looks very nice!

**Comment by rhiever** [comment]
@weixuanfu2016, we can do that separately in another PR. Merging this one before any other big changes happen and it needs to be rebased for the 20th time. :-)

**Pull request merged**
