### PR TITLE
Coveralls Coverage

### PR DESCRIPTION
**Pull request by rasbt**
Adding coverage reports and badge via coveralls.io -- also here, you need to log in and enable the repo.
Plus, I added Python 2.7 and 3.5 version badges and a GPLv3 license badge.

### CODE REVIEW

**Comment by rhiever** [comment]
Hmmm, there's no free version for coveralls.io?

**Comment by rasbt** [comment]
Coveralls should be free; I am using it for free :)

**Comment by rasbt** [comment]
See here: https://coveralls.io/pricing 

> OPEN 
SOURCE
Coveralls is and will always be free for open source projects. You can always add a subscription to get coverage reports on private repos later.

**Comment by rhiever** [comment]
Gotcha. I think I was confused by their aggressive push on upgrading to the pro version. I think it's set up now.

**Pull request merged**
