### PR TITLE
Tonyfast/imputer

### PR DESCRIPTION
**Pull request by tonyfast**
[please review the [contribution guidelines](http://rhiever.github.io/tpot/contributing/) prior to submitting your pull request. go ahead and delete this line if you've already reviewed said guidelines.]
## What does this PR do?

Add Imputer to the tpot preprocessors.
## Where should the reviewer start?

[`imputer.py`](https://github.com/tonyfast/tpot/blob/tonyfast/imputer/tpot/operators/preprocessors/imputer.py)
## How should this PR be tested?

_No tests were added mostly because there weren't any for the `preprocessors`
## What are the relevant issues?
#253
## Questions:
- Do the docs need to be updated?  _Yes._
- Does this PR add new (Python) dependencies? _No._

### CODE REVIEW

**Comment by teaearlgraycold** [comment]
A few things:

1. You'll need to add the Imputer to the preprocessor's `__init__.py` file so it is discovered by the operators module.
2. You should PR this onto the development branch.
3. You should add logic that makes it so the Imputer is always placed at the beginning of the pipeline if there are missing values in the input matrix. It probably doesn't ever need to be anywhere besides at the beginning of a pipeline, right?

**Comment by rhiever** [comment]
👍 to @teaearlgraycold's suggestions.

**Comment by tonyfast** [comment]
@rhiever @teaearlgraycold would the Imputer class handle the logic or would it go somewhere else?

**Comment by tonyfast** [comment]
Should the Imputer even be an option in the pipeline?  It seems like it would only be required when the fitting step beings if `np.isnan(features).any()`.

**Comment by rhiever** [comment]
I think the Imputer should only be added to the primitive set if there are any missing values in the data set.

**Comment by rhiever** [comment]
Sorry it's taken me forever to get to this. We will also need a unit test verifying that a pipeline with this imputer work -- both data sets with and without missing data (two separate tests).

**Pull request closed without merging**
