### PR TITLE
updated all XGB code for n_estimators removal

### PR DESCRIPTION
**Pull request by screwed99**
## What does this PR do?
Closing off the second half of #119 removing n_estimators from XGB operator.

## Where should the reviewer start?
I basically copied change for change from your first merge on this at #122 except that there is no test coverage for theXGBClassifier class (it appears because it is not taken from the `sklearn` package list the other classes are.

## How should this PR be tested?
I've run `nosetests -s -c` locally  (Python 3 conda environment) and CI should be doing the rest.

## Any background context you want to provide?
This is my first pull request ever so really any and all feedback thoroughly welcome!

## Questions:
I'm interested in learning a bit more about your suggested workflow for doing pull requests:
- The installation instructions for a user were in the documentation (and very clear) but I was wondering what conda environment  you would suggest setting up for development (I would guess installing the `tpot` package is not necessary and for all testing of changes just set your working directory to inside the clones git project?)
- Further to the above, the contribution guidelines mention CI but don't really mention how to test locally before committing, pushing and issues a pull request. I installed `nose` within my conda environment and ran `nosetests -s -v` as found in the CI files, is that sufficient?

### CODE REVIEW

**Comment by rhiever** [comment]
Many thanks, and nice work on your first PR. :+1: 

>I was wondering what conda environment you would suggest setting up for development (I would guess installing the tpot package is not necessary and for all testing of changes just set your working directory to inside the clones git project?)

Hmmm... we should probably add section to the contributor document answering this question. The short answer is:

* Use an install of the Anaconda Python distribution w/ Python 3, all packages updated to the latest version

* pip install the other dependencies (DEAP, XGBoost, etc.)

* Before making any changes to the code, create a new branch in your fork of the TPOT repo

* cd into the base TPOT directory, and when running TPOT during development:

    * import TPOT normally if using the script version -- make sure you don't have TPOT installed locally, just in case, so you know that you're using the dev version
    * Call TPOT on the command line with `python -m tpot.tpot`

>Further to the above, the contribution guidelines mention CI but don't really mention how to test locally before committing, pushing and issues a pull request. I installed nose within my conda environment and ran nosetests -s -v as found in the CI files, is that sufficient?

Yes, running nosetests in the base TPOT directory should run all the unit tests for you. We're still working on expanding the unit tests to cover more of the code base.

**Comment by screwed99** [comment]
OK great, thank-you for the feedback!

Can I go ahead and raise an issue for the contributor document changes and submit a pull request with the changes (unless you'd prefer doing it another way)?

**Comment by rhiever** [comment]
Yes, please feel free to do that. I will be happy to review the PR.

**Comment by stevenmaguire** [comment]
Congrats @screwed99!!!

**Pull request merged**
