### PR TITLE
fixing column masking & typo

### PR DESCRIPTION
**Pull request by rcarneva**
Two find-and-replaces:

1. Column masking in the exported pipeline wasn't working correctly for me with SelectKBest on a model since the mask was coming through as a numeric but some of the columns were named. Updated `[mask]` -> `.iloc[:, mask]` and it seems to work now, though more testing would be good if it was working as expected on your end.
2. `indeces` -> `indices`

### CODE REVIEW

**Comment by rhiever** [comment]
Thanks @rcarneva! Both versions work fine on my end, though I believe the `.iloc[:, mask]`syntax is "more correct." What version of Python/pandas are you running?

**Comment by rcarneva** [comment]
Python 2.7.10 / pandas 0.17.1

**Comment by rhiever** [comment]
Interesting. I'm on Python 3.5 / pandas 0.17.1 and both cases work.

**Comment by rcarneva** [comment]
Think I tracked it down. The two features in my training set had (integer) names 1 and 2, and so pandas seemed to have trouble applying the integer mask. Renaming the columns to strings made it work with the original code, but the updated version with `iloc` seems to work in both situations, so is probably a safer bet.

BTW, really neat idea and project.

**Comment by rhiever** [comment]
I had a feeling that was it. Thanks for looking into it!

>BTW, really neat idea and project.

Thanks! Happy to have you involved more if you have any ideas or any of the open issues catch your fancy.

**Pull request merged**
