### PR TITLE
Coveralls in travis

### PR DESCRIPTION
**Pull request by rasbt**
Just realized that there was no Travis built with nosetests coverage flags. This change should trigger coveralls properly now. Let's keep this pull request unmerged until we are sure that it works as intended

### CODE REVIEW

**Comment by rhiever** [comment]
OK, merge it when you think it looks good. :-)

**Comment by rasbt** [comment]
Yeah, sorry, these things are a bit messy, I am not sure if there is a (good) offline way to validate those files

**Comment by rasbt** [comment]
Okay, should be all set now and ready to be merged. Wow, but we really have to work a bit on the unit tests (coverage is 54%) :P There were a few things in the code that caught my eye: perfect candidates for refactoring, but that's a task for another day

**Comment by rhiever** [comment]
I'm amazed the coverage is even 54% right now tbh. Those were just some quick tests to get things rolling.

**Comment by rhiever** [comment]
Any idea why the coverage is still showing up as unknown? I guess it takes a while to update?

**Comment by rasbt** [comment]
I see. I think it literally just counts the lines of code that are executed during the unit tests divided by the total number of lines

**Comment by rasbt** [comment]
> Any idea why the coverage is still showing up as unknown on the repo? I guess it takes a while to update?

May be related to the github caching thing and will show up after time. If you click on the badge, you can see that it already points to the correct page:

screen shot 2015-11-16 at 4 39 20 pm

**Pull request merged**
