### PR TITLE
added onehotencoder which imports from auto-sklearn OneHotEncoder int…

### PR DESCRIPTION
**Pull request by slcott**
[please review the [contribution guidelines](http://rhiever.github.io/tpot/contributing/) prior to submitting your pull request. go ahead and delete this line if you've already reviewed said guidelines.]

## What does this PR do?

adds a onehotencoder

## Where should the reviewer start?

Look over onehotencoder.py. It's minimal. Follow the import to _auto_sklearn_onehotencoder.py.

## How should this PR be tested?

i'm guessing a unit test that creates and uses a onehotencoder 

## Any background context you want to provide?

For internal files, I referenced the following:
http://stackoverflow.com/a/7609651/629014

I added a prefix underscore to the auto-sklearn `OneHotEncoder`. 

Please, verify the license has been added to the top of the ported OneHotEncoder.py auto-sklearn file. Also, the filename convention I chose for the file may not be preferred.

## What are the relevant issues?

[you can link directly to issues by entering # then the number of the issue, for example, #3 links to issue 3]

#215 

## Questions:

- Do the docs need to be updated? yes
- Does this PR add new (Python) dependencies? no

…ernally

### CODE REVIEW

**Comment by mfeurer** [comment]
You maybe want to copy the tests from auto-sklearn as well to ensure it stays functional.

**Comment by rhiever** [comment]
Good idea @mfeurer. Do you have any advice for using this custom version of the OHE? I know you mentioned dropping support for non-sklearn classes in auto-sklearn. Do you plan to drop this custom OHE from auto-sklearn?

**Comment by rhiever** [comment]
@slcott, I'm 👍 on using the unit tests for @mfeurer's OHE implementation and putting them into `tests.py`. I think it will be important to maintain unit tests for new features such as this one.

**Comment by rhiever** [comment]
Also, please close this PR and send it to the `development` branch. The `master` branch is retained for the latest stable release of TPOT.

**Comment by slcott** [comment]
It looks like auto-sklearn OHE test is located [here](https://github.com/automl/auto-sklearn/blob/6acc1ae49727c22ecef30aacda8beccea7632f07/test/test_pipeline/implementations/test_OneHotEncoder.py) 

This is the only sklearn import it uses: `
from sklearn.utils.testing import assert_array_almost_equal`

I changed the PR target to `development`, but didn't create a new PR. Does that work correctly? 

[It looks like I can add more commits to my branch and in the unit test](http://stackoverflow.com/a/9790530/629014). Still getting used to this PR thing.

**Comment by rhiever** [comment]
Yes, that's right. If you commit against the branch that you sent the PR from, then they will automatically update on the PR. Those unit tests look like good ones to add.

**Comment by slcott** [comment]
I'm gonna close this PR as suggested and submit another [located at](https://github.com/rhiever/tpot/pull/256)

**Comment by mfeurer** [comment]
I'm not planning to remove support for custom code from auto-sklearn, that should still be possible through a plug-in like mechanism. What I want is to remove custom ML code from auto-sklearn as much as possible to make the package lean. ML code should reside in packages built for that, like scikit-learn or xgboost.

In the long run, the OneHotEncoder in its current form will be removed and replaced by a feature union, which allows a separate processing flow for categorical and numerical attributes. I'm not sure though what this means for the feature which removes seldom values and replaces them by an 'other' indicator. My advice is to use this 'other' indicator, it proved helpful for datasets where categorical attributes have lots of values. Before we had that, auto-sklearn would very often choose FeatureAgglomeration for feature preprocessing to reduce the number of features again.

**Pull request closed without merging**
