### PR TITLE
Useful research features

### PR DESCRIPTION
**Pull request by kuratsak**
## What does this PR do?
Adds a couple of really cool features I use working with this tool.
I believe other people would want at least some of these too.
See commit messages for the full feature list :muscle: 

## Where should the reviewer start?
Not sure, just take a look at each commit, they are split to separate features relatively nicely.

## How should this PR be tested?
For the periodic pipelines: try using the -psp argument and see your supplied folder start getting pipelines after each generation -
 make generations size 2 for example so you'll get some output pipelines.
For the manual scorer, just add my_scorer.py file in work dir when running tpot, and enter my_scorer.my_function and see the magic happen.

## Any background context you want to provide?
I run heavy duty ML projects on a local research machine I got at work, these features make it much easier to investigate and follow the process while not stopping it during its work.

## What are the relevant issues?

[you can link directly to issues by entering # then the number of the issue, for example, #3 links to issue 3]

## Questions:

- Do the docs need to be updated? I don't believe so, these are just some improvements.
- Does this PR add new (Python) dependencies? Nope.

### CODE REVIEW

**Comment by kuratsak** [comment]
I will be back sunday, will fix anything that rises here of course.
Sorry if I'm not responsive during my weekend, I can't take my work machine home with me.

**Comment by kuratsak** [comment]
Saw python 3 broke, I have a local python 2 environment only, will fix the python 3 stuff in the close days.

**Comment by teaearlgraycold** [comment]
I would recommend PRing most of these commits individually. Some of them (like using `assert_equal`) are useful and easy to review, but others may not be accepted or would take much longer to review.

**Comment by kuratsak** [comment]
I assumed it's less work this way. Most of them are relatively small. Of it
helps, I can open PRs on each..

**Comment by rhiever** [comment]
I agree with @teaearlgraycold's suggestion. It would be easier to make a separate branch and PR for each feature so we can review and discuss them individually. This PR contains quite a few changes that would be difficult to review and process all together. Thanks again for sending these enhancements in!

**Comment by kuratsak** [comment]
I will separate all the bug fixes into one and each feature into a separate
one if it helps.

**Comment by rhiever** [comment]
👍

**Comment by rhiever** [comment]
Will close this PR in the meantime.

**Pull request closed without merging**
