### PR TITLE
Documenting Pipeline Operators / Public Functions

### PR DESCRIPTION
**Pull request by bartleyn**
This is intended to be an enhancement to the documentation of the pipeline operators & public functions of the main TPOT class. Naturally this is just a first stab at formatting the pages, but hopefully we will not have to change much for the big refactor. At the very least there is some content for each of the operators & functions. I've also changed the theme and mkdocs config to help incorporate navigation to the new reference.

### CODE REVIEW

**Comment by rhiever** [comment]
>This branch has conflicts that must be resolved

Know what's causing that conflict?

**Comment by bartleyn** [comment]
My mkdocs.yml was the source of the conflict. Seems resolved.

**Comment by rhiever** [comment]
Great start! I think the "example exported code" would also need to include the import statements for the corresponding operator, right?

**Comment by bartleyn** [comment]
You're totally right. I reused the first part for all of the examples, and neglected to update import statements. I'll throw those in when I get a chance.

**Comment by rhiever** [comment]
Also please note that in #72 PCA was changed to RandomizedPCA. The operator is still named `_pca`, but it calls RandomizedPCA instead.

**Comment by bartleyn** [comment]
Changes should be integrated.

**Comment by rhiever** [comment]
Merged - thanks again!

**Pull request merged**
